learning_log/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url


urlpatterns = [
    path('admin/', admin.site.urls),
    # path('', include('learning_logs.urls', namespace='learning_logs')),
    url(r'', include('learning_logs.urls', namespace='learning_logs'))
]

learning_logs/urls.py
# -*- coding: utf-8 -*-

'''
@Time    : 2020/7/26 18:44
@Author  : Wanhao Zhang
@Contact : 1809721229@qq.com 
@FileName: urls.py
@Software: PyCharm
 
'''

# 定义 learning_logs 的URL模式
from django.conf.urls import url
from . import views

app_name = 'learning_logs'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^topics/$', views.topics, name='topics'),
    url(r'^topic/(?P<topic_id>\d+)/$', views.topic, name='topic'),
    url(r'^new_topic/$', views.new_topic, name='new_topic'),
    url(r'^new_entry/(?P<topic_id>\d+)/$', views.new_entry, name='new_entry'),
    url(r'^edit_entry/(?P<entry_id>\d+)/$', views.edit_entry, name='edit_entry'),
]

learning_logs/models.py
from django.db import models

# Create your models here.

class Topic(models.Model):
    text = models.CharField(max_length= 200)
    date_added = models.DateTimeField(auto_now_add= True)
    def __str__(self):
        return self.text

class Entry(models.Model):

    topic = models.ForeignKey(Topic, on_delete= models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add= True)

    class Meta:
        verbose_name_plural = 'entries'

    def __str__(self):
        return self.text[:50] + "..."

users/models.py
from django.db import models

# Create your models here.

learning_logs/forms.py
# -*- coding: utf-8 -*-

'''
@Time    : 2020/7/28 20:28
@Author  : Wanhao Zhang
@Contact : 1809721229@qq.com 
@FileName: forms.py
@Software: PyCharm
 
'''
from django import forms

from .models import Topic
from .models import Topic, Entry

class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['text']
        labels = {'text': ''}


class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text': ''}
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}

learning_logs/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
# Create your views here.
from .models import Topic, Entry
from .forms import TopicForm, EntryForm

def index(request):
    # index
    return render(request, 'learning_logs/index.html')

def topics(request):
    topics = Topic.objects.order_by('date_added')
    context = {'topics': topics}
    return render(request, 'learning_logs/topics.html', context)

def topic(request, topic_id):
    topic = Topic.objects.get(id=topic_id)
    entries = topic.entry_set.order_by('-date_added')
    context = {'topic': topic, 'entries': entries}
    return render(request, 'learning_logs/topic.html', context)

def new_topic(request):
    """Add a new topic."""
    if request.method != 'POST':
        # No data submitted; create a blank form.
        form = TopicForm()
    else:
        # POST data submitted; process data.
        form = TopicForm(request.POST)
        if form.is_valid():
            new_topic = form.save(commit=False)
            new_topic.owner = request.user
            new_topic.save()
            return HttpResponseRedirect(reverse('learning_logs:topics'))

    context = {'form': form}
    return render(request, 'learning_logs/new_topic.html', context)


def new_entry(request, topic_id):
    """Add a new entry for a particular topic."""
    topic = Topic.objects.get(id=topic_id)

    # if topic.owner != request.user:
    #     raise Http404

    if request.method != 'POST':
        # No data submitted; create a blank form.
        form = EntryForm()
    else:
        # POST data submitted; process data.
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.save()
            return HttpResponseRedirect(reverse('learning_logs:topic',
                                                args=[topic_id]))

    context = {'topic': topic, 'form': form}
    return render(request, 'learning_logs/new_entry.html', context)


def edit_entry(request, entry_id):
    """Edit an existing entry."""
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic
    # if topic.owner != request.user:
    #     raise Http404

    if request.method != 'POST':
        # Initial request; pre-fill form with the current entry.
        form = EntryForm(instance=entry)
    else:
        # POST data submitted; process data.
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('learning_logs:topic',
                                                args=[topic.id]))

    context = {'entry': entry, 'topic': topic, 'form': form}
    return render(request, 'learning_logs/edit_entry.html', context)

users/views.py
from django.shortcuts import render

# Create your views here.

learning_logs/templates/learning_logs/base.html
{% load bootstrap3 %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Learning Log</title>

    {% bootstrap_css %}
    {% bootstrap_javascript %}

  </head>

  <body>


{#  <nav class="navbar navbar-default">#}
{#  <div class="container-fluid">#}
{#    <!-- Brand and toggle get grouped for better mobile display -->#}
{#    <div class="navbar-header">#}
{#      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">#}
{#        <span class="sr-only">Toggle navigation</span>#}
{#        <span class="icon-bar"></span>#}
{#        <span class="icon-bar"></span>#}
{#        <span class="icon-bar"></span>#}
{#      </button>#}
{#      <a class="navbar-brand" href="#">Brand</a>#}
{#    </div>#}
{##}
{#    <!-- Collect the nav links, forms, and other content for toggling -->#}
{#    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">#}
{#      <ul class="nav navbar-nav">#}
{#        <li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li>#}
{#        <li><a href="#">Link</a></li>#}
{#        <li class="dropdown">#}
{#          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>#}
{#          <ul class="dropdown-menu">#}
{#            <li><a href="#">Action</a></li>#}
{#            <li><a href="#">Another action</a></li>#}
{#            <li><a href="#">Something else here</a></li>#}
{#            <li role="separator" class="divider"></li>#}
{#            <li><a href="#">Separated link</a></li>#}
{#            <li role="separator" class="divider"></li>#}
{#            <li><a href="#">One more separated link</a></li>#}
{#          </ul>#}
{#        </li>#}
{#      </ul>#}
{#      <form class="navbar-form navbar-left">#}
{#        <div class="form-group">#}
{#          <input type="text" class="form-control" placeholder="Search">#}
{#        </div>#}
{#        <button type="submit" class="btn btn-default">Submit</button>#}
{#      </form>#}
{#      <ul class="nav navbar-nav navbar-right">#}
{#        <li><a href="#">Link</a></li>#}
{#        <li class="dropdown">#}
{#          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>#}
{#          <ul class="dropdown-menu">#}
{#            <li><a href="#">Action</a></li>#}
{#            <li><a href="#">Another action</a></li>#}
{#            <li><a href="#">Something else here</a></li>#}
{#            <li role="separator" class="divider"></li>#}
{#            <li><a href="#">Separated link</a></li>#}
{#          </ul>#}
{#        </li>#}
{#      </ul>#}
{#    </div><!-- /.navbar-collapse -->#}
{#  </div><!-- /.container-fluid -->#}
{#</nav>#}

    <!-- Static navbar -->
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">

        <div class="navbar-header">

          <button type="button" class="navbar-toggle collapsed"
              data-toggle="collapse" data-target="#navbar"
              aria-expanded="false" aria-controls="navbar">
          </button>

          <a class="navbar-brand" href="{% url 'learning_logs:index' %}">LogWeb</a>

        </div>


        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li><a href="{% url 'learning_logs:topics' %}">Topics</a></li>
          </ul>
        </div><!--/.nav-collapse -->

      </div>

    </nav>

    <div class="container">

      <div class="page-header">
        {% block header %}{% endblock %}
      </div>
      <div>
        {% block content %} {% endblock %}
      </div>

    </div> <!-- /container -->

  </body>
</html>

learning_logs/templates/learning_logs/edit_entry.html
{% extends "learning_logs/base.html" %}
{% load bootstrap3 %}
{% block header %}
    <h2>
       Edit entry:
    </h2>
{% endblock header %}
{% block content %}

  <h3><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></h3>

    
  <form action="{% url 'learning_logs:edit_entry' entry.id %}" method='post'>
    {% csrf_token %}
{#    {{ form.as_p }}#}
    {% bootstrap_form form %}

{#        {% buttons %}#}
{#            <button type="button" class="btn btn-default btn-lg" name="submit">#}
{#            <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>#}
{#            add topic#}
{#            </button>#}
{#        {% endbuttons %}#}


        {% buttons %}
            <button name="submit" class="btn btn-default btn-lg"><span class="glyphicon glyphicon-pencil" aria-hidden="true"></span> &nbsp; Save changes</button>
        {% endbuttons %}

{#    <button name="submit">save changes</button>#}
  </form>

{% endblock content %}

learning_logs/templates/learning_logs/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    {% extends "learning_logs/base.html" %}

    {% block header %}
        <h4>Welcome to the LogWeb, you can edit whatever you want.</h4>
        <h6>There is no function for deleting topics or entries, so I hope you can add something meaningful, not for testing my web. HAVE FUN!</h6>
    {% endblock header %}
{##}
    {% block content %}
        <div class="jumbotron">
            <div class="container">
                <h3>在这里，你可以分享你喜欢的一切，不论是感情、句子、大事小事</h3>
                <h3>你也可以把这里当作自己的树洞，任何开心、不开心的都一吐为快</h3>
{#                <h3>在这里，我们都是陌生人，</h3>#}
                <h3>最后，请善用edit功能，你可以在里面增加自己的评论，但请不要修改别人的分享</h3>
{#                <h3>Never give up</h3>#}
{#                <h3>Look ahead</h3>#}
{#                <h3>Stay positive</h3>#}
{#                <h3>Do all you can.</h3>#}
{#                <br>#}
{#                <p font-size="8">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;摘自：高中英语阅读理解</p>#}
            </div>
        </div>
    {% endblock content %}
</body>
</html>

learning_logs/templates/learning_logs/new_entry.html
{% extends "learning_logs/base.html" %}
{% load bootstrap3 %}
{% block header %}
    <h2>
        Add a new entry:
    </h2>
{% endblock header %}

{% block content %}

  <h3>
    <a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a>
  </h3>

{#  <form action="{% url 'learning_logs:new_entry' topic.id %}" method='post'>#}
{#    {% csrf_token %}#}
{#    {{ form.as_p }}#}
{#    <button name='submit'>add entry</button>#}
{#  </form>#}


    <form action="{% url 'learning_logs:new_entry' topic.id %}" method='post' class="form">
        {% csrf_token %}

{#        {{ form.as_p }} <!--显示表单-->#}
        {% bootstrap_form form %}

{#        {% buttons %}#}
{#            <button type="button" class="btn btn-default btn-lg" name="submit">#}
{#            <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>#}
{#            add topic#}
{#            </button>#}
{#        {% endbuttons %}#}


        {% buttons %}
            <button name="submit" class="btn btn-default btn-lg"><span class="glyphicon glyphicon-pencil" aria-hidden="true"></span> &nbsp; Add entry</button>
        {% endbuttons %}


    </form>

{% endblock content %}

learning_logs/templates/learning_logs/new_topic.html
{% extends "learning_logs/base.html" %}

{% load bootstrap3 %}

{% block header %}
    <h2>
        Add a new topic:
    </h2>
{% endblock header %}


{% block content %}

    <form action="{% url "learning_logs:new_topic" %}" method="post" class="form">
        {% csrf_token %}

{#        {{ form.as_p }} <!--显示表单-->#}
        {% bootstrap_form form %}

{#        {% buttons %}#}
{#            <button type="button" class="btn btn-default btn-lg" name="submit">#}
{#            <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>#}
{#            add topic#}
{#            </button>#}
{#        {% endbuttons %}#}


        {% buttons %}
            <button name="submit" class="btn btn-default btn-lg"><span class="glyphicon glyphicon-pencil" aria-hidden="true"></span> &nbsp; Add topic</button>
        {% endbuttons %}


    </form>

{% endblock content %}

learning_logs/templates/learning_logs/topic.html
{% extends 'learning_logs/base.html' %}

{% block header %}
  <h2>{{ topic }}</h2>
{% endblock header %}

{% block content %}


    <button type="button" class="btn btn-default btn-lg">
{#      <span class="glyphicon glyphicon-menu-right" aria-hidden="true"></span>#}
        <a href="{% url 'learning_logs:new_entry' topic.id %}">Add new entry</a>
    </button>

    <br>
    <br>


  {% for entry in entries %}
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3>
          {{ entry.date_added|date:'M d, Y H:i' }}
          <small>
            <a href="{% url 'learning_logs:edit_entry' entry.id %}">
              edit entry</a>
          </small>
        </h3>
      </div>
      <div class="panel-body">
        {{ entry.text|linebreaks }}
      </div>
    </div> <!-- panel -->
  {% empty %}
    There are no entries for this topic yet.
  {% endfor %}

{% endblock content %}

learning_logs/templates/learning_logs/topics.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>topics</title>
</head>
<body>
{% extends "learning_logs/base.html" %}

{% block header %}
    <h2>Topics</h2>
{% endblock header %}

{% block content %}
{#    <p>topics</p>#}

    <ul>
        {% for topic in topics %}
            <li>
                <h3>
                    <a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a>
                </h3>
            </li>
            {% empty %}
            <li>No topics have been added.</li>
        {% endfor %}
    </ul>

    <br>

    <button type="button" class="btn btn-default btn-lg">
      <span class="glyphicon glyphicon-menu-right" aria-hidden="true"></span>
            <a href="{% url 'learning_logs:new_topic' %}">Add new topic</a>
    </button>

{% endblock %}

</body>
</html>